### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by reslear** [reslear/CapacitorGoogleAuth-Vue3-example#1]
- [ ] update plugin with support:
https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/136
https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/114
- [ ] migrate to `ts` config
- [ ] refactor code for iOS
